TEST= gui/sxako_gui

OTHERTEST += $(TEST)

$(OBJDIR)/$(TEST): general.so gui.so

$(OBJDIR)/gui/%: CFLAGS += \
	$$(pkg-config --cflags gtkmm-3.0 | sed 's/-\<I\>/-isystem/g') \
	$$(pkg-config --cflags librsvg-2.0 | sed 's/-\<I\>/-isystem/g')

$(OBJDIR)/gui/%: LDFLAGS += \
	$$(pkg-config --libs gtkmm-3.0) \
	$$(pkg-config --libs librsvg-2.0)
