#!/bin/bash

var=$1
rep=$2

sed '
s/\\input{test.settings}/\\input{'$2'.settings}/

s/\\begin{drawing}{'$1'-\(.*\)}/%\
\\tikzsetnextfilename{'$2'-\1}%\n\\begin{tikzpicture}\n\\bb/

s/\\begin{drawing}{\(.*\)-'$1'}/%\
\\tikzsetnextfilename{\1-'$2'}%\n\\begin{tikzpicture}\n\\bb/

s/\\begin{drawing}{.*}/%\
\\tikzset{external\/export next=false}%\n\\begin{tikzpicture}/

s/\\end{drawing}/\\end{tikzpicture}/'
